### ISSUE TITLE
fast 10x1024 decoder

### ISSUE THREAD

**Issue by FredericaBernkastel** [FredericaBernkastel/Cellular-automaton#1]
[`decoder 10x1024.mc`](https://github.com/FredericaBernkastel/Cellular-automaton/blob/master/JvN/big%20sandbox/decoder%2010x1024.mc) [`[IMG]`](https://github.com/FredericaBernkastel/Cellular-automaton/blob/master/JvN/big%20sandbox/decoder%2010x1024.png)
Yh, i really need to reduce size of it.
OR
Lets build `segment:offset` addressing type for my 256kbit [ROM module](https://github.com/FredericaBernkastel/Cellular-automaton/blob/master/JvN/big%20sandbox/256k%20ROM.mc).

**Comment by Lambdadelta3** [comment]
I basically made a binary tree decoder as can be seen here:
![10x1024 decoder binary tree](https://user-images.githubusercontent.com/34716366/45916223-a6d74b80-be62-11e8-9399-1358689f61de.png)


the structure used and its explanation is here:
![decoder sandbox](https://user-images.githubusercontent.com/34716366/45915634-62df4900-be58-11e8-8d9d-3772c4bf21c5.png)

Worst case scenario goes from 23700 frames (old one) to 6700(this one), you can obviously add more divisions and this should improve it with some diminishing returns, this is just a prototype for the idea so i didnt extend too much on it. Its worth noticing that i didnt use a new decoder design, but rather used the one with 10 bits of input while only using 8 of them, so that is something that should be changed.

[Memory file](https://drive.google.com/open?id=18FnXFJr2IH76GNJlSSCRhxFmFVwhCUcv)
[Memory Sandbox file](https://drive.google.com/open?id=1JndVA0gT4GyfgbazwKsySPK64zIlLju_)

**Comment by Lambdadelta3** [comment]
Fixed the problem that left the path changed if a bit was 0.

New design used:
![decoder sandbox fixed](https://user-images.githubusercontent.com/34716366/45921733-9b643e80-bebb-11e8-9037-a8c5e26c92cf.png)

It's basically the same with the interrupter added in. 

[fixed decoder file ](https://drive.google.com/open?id=1gZRhecRYih4GRfgV5xD-kC0A2dqstlve)
